### PR TITLE
Migrating to AndroidX

### PR DESCRIPTION
**Pull request by MuhammadUzair**
## Motivation

Android build is failed if  we add `react-native-image-picker` in react-native latest version (0.59.9) because of AndroidX.
In this PR ,I fixed android build issue for AndroidX.

## Google Guide
https://developer.android.com/jetpack/androidx/migrate

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
Have you tested the changes with older versions of react native? 
I'll do some testing my side too.  

Thanks!

**Comment by MuhammadUzair** [comment]
Not tested in older versions

**Comment by Johan-dutoit** [comment]
FWIW, the library works fine on 0.59.9 without these changes (on my side anyway). 
That being said, it's definitely required for the new 0.60.0 that's about to drop.

Let us both (and hopefully more) do some additional testing so that we can release this.

**Comment by Johan-dutoit** [comment]
Let's keep this open, as it'll most likely get merged soon.

**Comment by niteshgrg** [comment]
I also get error in react-native 0.59.9. Would be good to have this merged soon.

**Comment by fleita9** [comment]
com.imagepicker.testing.TestableImagePickerModule.java is also importing android.support.annotation classes.

`Task :react-native-image-picker:compileDebugUnitTestJavaWithJavac FAILED
/home/fleita/desarrollo/humber/temp/apk/node_modules/react-native-image-picker/android/src/test/java/com/imagepicker/testing/TestableImagePickerModule.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/home/fleita/desarrollo/humber/temp/apk/node_modules/react-native-image-picker/android/src/test/java/com/imagepicker/testing/TestableImagePickerModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/home/fleita/desarrollo/humber/temp/apk/node_modules/react-native-image-picker/android/src/test/java/com/imagepicker/testing/TestableImagePickerModule.java:6: error: package android.support.annotation does not exist
import android.support.annotation.StyleRes;`
