### ISSUE TITLE
package com.imagepicker does not exist import com.imagepicker.ImagePickerPackage

### ISSUE THREAD

**Issue by aujisti-ador** [react-native-community/react-native-image-picker#960]
i am working on "react-native": "0.55.4". i was implementing image picker but when i run it i got this error:
----------------------------------------------
Task :app:compileDebugJavaWithJavac FAILED
D:\React Native App\xxx\android\app\src\main\java\com\xxx\MainApplication.java:10: error: package com.imagepicker does
not exist
import com.imagepicker.ImagePickerPackage;
                      ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
----------------------------------
Can anyone help?

**Comment by mtsaryk** [comment]
I have the same problem in the same RN version.

**Comment by feialoh** [comment]
I had the same problem on RN 0.57.8, I did all the troubleshooting as mentioned in another post like linking, checking dependency, cleaning build but none of them worked. Then I noticed in my MainApplication.java, it seem to have 2 references of image picker
```
import com.imagepicker.ImagePickerPackage;
import com.reactnative.ivpusic.imagepicker.PickerPackage;
```

I commented out the first one showing the error and also the ImagePickerPackage() below this and did a gradlew clean and Voila! Now it seems to work flawlessly.

**Comment by MayoudP** [comment]
getting this error after having upgraded from 2.X.X to 3.X.X ...
Running `-rm -rf node_modules, ./gradlew clean, yarn install, ...` nothing worked. Any ideas why ?

**Comment by rcidt** [comment]
@MayoudP did you find a solution?

**Comment by SyedHamzaHussain000** [comment]
Hello Guyz

**Comment by riteshp112** [comment]
I am facing the same issue.

**Comment by mrdahal123** [comment]
hello guy's i recently faced the same issue , i tried to uninstall the package and remove all add file in build.gradle and all , after that i checked my MainApplication.java and   --> import com.imagepicker.ImagePickerPackage; disable this then ./gradlew clean and yes it's working now .
